### ISSUE TITLE
Android is a 32bit build

### ISSUE THREAD

**Issue by utack** [Alberto97/android_device_motorola_addison#1]
Hi, is there a reason this is a 32bit build?  
From the Board config:

> TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi  
  
That is a lot of wasted performance, can we switch to a 64bit build?
Edit: apparently not wasted perfomance fwiw
Thanks

**Comment by GtrCraft** [comment]
Stock is not 64 bit too. And it's overrated anyway, no wasted performance at all

**Comment by utack** [comment]
Yes I found out about stock  
Performance seems kinda relevant:  
https://www.youtube.com/watch?v=TDBTiwjTT0k#t=9m20s  
Also for some native apps that are compiled for armv8

**Comment by GtrCraft** [comment]
Complain at moto, all apps are built for 32 and 64 bit and will work the same. If you want 64 bit then buy a 64 bit device

**Comment by utack** [comment]
Very funny about buying the 64bit device, Lenovorola does not mention it in a word, and tech reviewers never mentioned it either.  
So can the ROM be built in 64bit mode, or does it not work for a device that came with a 32bit stock rom for some reason?

**Comment by flareblitz21** [comment]
Some apps *cough* *cough* *Dolphin* require a 64 bit system and even if having a 64 bit system does not improve performance, it allows users more customization and ability to get 64 bit apps

**Comment by faiyazsheth** [comment]
it is 64bit now. go check XDA for builds. @Alberto97 think you can close this issue now. :D

**Comment by utack** [comment]
Yep sorry, I missed closing it.  🎉
